### ISSUE TITLE
Would be nice to have if we could customize permission sets by foundation

### ISSUE THREAD

**Issue by singhvishalk** [ArnaLabs/C9Cli#2]
We have a pretty common scenario where we don't want end users to have the ability to self provision elevated permissions through the cli for our Prod foundation, would be nice if admin could set flags at the foundation level that would define what permission can be assigned or not.

**Comment by rv2023** [comment]
@singhvishalk , Those options has been added as part of config.yml. please use latest version of cli and add the below entires to yml file:
  EnableASG: true
  SetOrgAuditor: true
  SetOrgManager: true
  SetSpaceAuditor: true
  SetSpaceManager: true
  SetSpaceDeveloper: true
